name: Execute Yandex Cloud CLI command
author: Nikita Volkov
inputs:
  key:
    description: YC service account key
    required: true
  args:
    description: Arguments to the `yc` command
    required: true
outputs:
  output:
    description: Command output
runs:
  using: docker
  image:
  env:
    key: ${{ inputs.key }}
    args: ${{ inputs.args }}
