name: Execute Yandex Cloud CLI command
author: Nikita Volkov
inputs:
  key:
    description: YC service account key
    required: true
  args:
    description: Arguments to the `yc` command
    required: true
outputs:
  output:
    description: Command output
runs:
  using: docker
  image: docker://ghcr.io/nikita-volkov/yc-cli.github-action:dff9e8d07a9ca2ff39d79e0c8f57fa8335b7f214
  env:
    key: ${{ inputs.key }}
    args: ${{ inputs.args }}
