name: Execute Yandex Cloud CLI command
author: Nikita Volkov
inputs:
  key:
    description: YC service account key
    required: true
  args:
    description: Arguments to the `yc` command
    required: true
outputs:
  output:
    description: Command output
runs:
  using: docker
  image: docker://ghcr.io/nikita-volkov/yc-cli.github-action:8f1984151b9a7702c206818d612eb0b679cb920b
  env:
    key: ${{ inputs.key }}
    args: ${{ inputs.args }}
