name: Execute Yandex Cloud CLI command
description: Automates installation and configuration of CLI and runs any command quickly
author: Nikita Volkov
inputs:
  key:
    description: YC service account key
    required: true
  args:
    description: Arguments to the `yc` command
    required: true
outputs:
  output:
    description: Command output
runs:
  using: docker
  image: docker://ghcr.io/nikita-volkov/yc-cli.github-action:868302bdf9eef03e45ff6e5c3b158887c16e9d30
  env:
    key: ${{ inputs.key }}
    args: ${{ inputs.args }}
