
on:
  push:
    branches:
      - major
      - minor
      - patch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: docker
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update action.yml
        uses: fjogeleit/yaml-update-action@v0.10.0
        with:
          valueFile: action.yml
          propertyPath: runs.image
          value: docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          updateFile: true
          commitChange: false

      - id: update-image-ref
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update docker image ref
          file_pattern: action.yml

      - id: tag
        name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          release_branches: major,minor,patch
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.ref_name }}
          commit_sha: ${{ steps.update-image-ref.outputs.commit_hash }}

      - name: Release
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.ref_name }}
          tag: ${{ steps.tag.outputs.new_tag }}
