
on:
  push:
    branches:
      - major
      - minor
      - patch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: docker
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update action.yml
        uses: fjogeleit/yaml-update-action@v0.10.0
        with:
          valueFile: action.yml
          propertyPath: runs.image
          value: docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          updateFile: true
          commitChange: false

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update docker image
          file_pattern: action.yml

      - name: Release
        id: get-version
        # Using the older version due to (until fixed):
        # https://github.com/anothrNick/github-tag-action/issues/139
        uses: anothrNick/github-tag-action@1.36.0
        env:
          RELEASE_BRANCHES: major,minor,patch
          INITIAL_VERSION: v0.0.0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ github.ref_name }}
          WITH_V: true
